language: node_js

node_js:
- 7

before_install:
- openssl aes-256-cbc -K $encrypted_294e4e77ddf7_key -iv $encrypted_294e4e77ddf7_iv
  -in travis-service-account-auth.json.enc -out travis-service-account-auth.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test

after_success:
- npm run coveralls
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
- npm run build

deploy:
  provider: script
  script: internals/scripts/deploy.sh
  on:
    branch: production
  skip_cleanup: true

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
  - node_modules
