language: node_js

node_js:
- 7

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test

after_success:
- npm run coveralls
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
- npm run build

deploy:
  provider: gcs
  access_key_id: $GCS_INTEROPERABLE_ACCESS_KEY_ID
  secret_access_key: $GCS_INTEROPERABLE_ACCESS_SECRET
  bucket: $GCS_BUCKET
  skip_cleanup: true
  acl: public-read


notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
  - node_modules
