language: node_js

node_js:
- 7

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
  - pip install awscli

script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test
- npm run build

after_success: npm run coveralls

deploy:
  provider: s3
  bucket: $AWS_BUCKET
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
  acl: public_read
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
  - node_modules
