language: node_js

node_js:
- 7

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install cloudfront-invalidate-cli

script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test

after_success:
- npm run coveralls
- npm run build

deploy:
  provider: s3
  bucket: $AWS_BUCKET
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
  acl: public_read
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

after_deploy:
- cf-invalidate -- $AWS_CLOUDFRONT_DISTRIBUTION_ID "/*"

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
  - node_modules
