language: node_js

node_js:
- 7

deploy:
  provider: s3
  access_key_id:
    secure: "vCKFIFU58pBxXgPn51zYKQTfHfb7hU/vxPMocuksTOfLJiOr8dKnA1FUvkFxKjHxMnKpnqUGdCOQjaTewyDqCAZzQhx+t/uFM792xZu7AM1W13B2jbCbaKiWIArsQMSV322s8BgSwZxyOil2bH7Wcbzcl7KPNJx69qR8CKdJd3GsbZ/AS/Ph4Z3G40LZzJGQm6Rem5JuXXHH5pjiCuupLswdC0i41jwmEpdXdKcucMneh9htF5Gq5gYhABMguvZF/HnMjWdkgJoG+xUgjV0/KHnButtubIJpOsYl05i1n+sAUGxSPQ68X5T+qgViZuM1NIYkny3SFn6y+rAGGq4d08OfKNK9L5UJMoAAb1rPTCA29RDafHJ4MHxKhXINhFJ50PDfscpUAan021qrDdjNjWdSmg+ji+L7u6m4uSBaIqd1Yay5gdAnlXqfPbw8oJA54a4cx4lsYQKGXYCDjEAqK9tbUQQwDnx+LJE2jJt8ItMYJPYH7Id7+cfz8RclluHXonh51ICKxPMVK4EWbH+oz+Vl5b/I99r3wb8z87Wk96bz6HIE1CCN6prnB7hxYUY7PNVd1dYrIPyk5dWl21kWvaQBkzTM/rZETa0ywPtrkZYkggmGCNM9YPUwfXE880HzhZegDmqpTfg2oACRJ5HvMT2nNYl6NF7xFPoXoUPctEg="
  secret_access_key:
    secure: "C23Yq38JRzhOGORIuscdOSUVJbfKOc+GGNDMk7Fc/Yp/zWQCloQ27yyS/MlC4gC3a4u5gzGoYVb5ZHVPTk9OJjAxvYjTNws/PsQupgJfRLKfVgaeTggkMFBzM3Oaf+7WLroNti38+D+EeSrm3kbRI/24/o1HkyEawcLw7dsfu26An8fgANln7pOx1+qAdSb1F+aCZaKdFRGUMPIGRM1UW0J6uDJw9a1jcQxfzWREZDtmHqqU56179UJdS+rUZVXJ0sk11ChWax7rT8EVqL8j7gNinKVodBQ4INFx7oN4vPewE8uXOmZglVnwx8RzYZsLsGEPWY290ncuu5R9mVvzOkG6xynmSH3Yia9jRuo1SI5BjBB5YzM34Xdn3E9q+iuJ4qkr/QajVZo7e2726ftqOXD1mF5ukefnKlmuHny2YAegGK+pTBrCEKVf7/4j6GbXArw0nhsheXMAuiaG2/pfdpKtPL/k2qOxp9cxdT5SBzmvba3nH04viVHQr0E9C59Vszz0tmjk+pccRP52NoB9WnsJriODbBBKmNqxzXyZbGN/4zwKGFCEohk239f0OQoNDM/cEP2KTJnhZSbvX4gFx23XpRhq1n0Jt10qK4j86T/6hUkBayCe+Wk7aRhOpKpce2BXPcI6cndUkIihcOOFewqH2e5jAcCPyXWThDOE1bw="
  bucket: "rocketleaguesam-web.s3.amazonaws.com"
  local_dir: build
  skip_cleanup: true

script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test
- npm run build

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: npm run coveralls

after_deploy:
  - ./.travis/reset-cloudfront-cache.sh

cache:
  yarn: true
  directories:
  - node_modules
